server:
  port: 80
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    #    表示是否将自己注册进eurekaserver默认为true
    register-with-eureka: true
    #    是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #    主机名称修改
    instance-id: order80
    # 访问路径可以显示IP
    prefer-ip-address: true