server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
#    sleuth:
#      sampler:
##        采样率0-1之间，1表示全采集
#        probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
#    表示是否将自己注册进eurekaserver默认为true
    register-with-eureka: true
#    是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
#    主机名称修改
    instance-id: payment8001
#    访问路径可以显示IP
    prefer-ip-address: true
#    Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 1
#    Eureka服务端在收到最后一次心跳后等待的时间间隔，单位为秒，（默认是90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities