server:
  port: 80
eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
ribbon:
  #  指的是建立连接后从服务读取到可用资源所用的时间
  ReadTimeout: 6000
  #  指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ConnectTimeout: 6000
spring:
  application:
    name: cloud-provider-hystrix-order
#   feign集成hystrix，此注解开启hystrix
feign:
  hystrix:
    enabled: true